name: Deploy Storybook

on:
  push:
    branches:
      - feature/server-build

env:
  PROJECT_NAME: ui-experiments
  TEMP_DIR: /home/${{ secrets.SSH_USER }}/temp
  DOCKER_FILE: ./docker.storybook

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: storybook

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Transfer files to server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.'
          target: '${{ env.TEMP_DIR }}'
          strip_components: 0

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@master
        env:
          TEMP_DIR: ${{ env.TEMP_DIR }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          DOCKER_FILE: ${{ env.DOCKER_FILE }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: TEMP_DIR,PROJECT_NAME,DOCKER_FILE
          script: |
            cd $TEMP_DIR
            IMAGE_NAME=$PROJECT_NAME:latest
            docker stop $PROJECT_NAME || true
            docker rm $PROJECT_NAME || true
            docker rmi $IMAGE_NAME || true

            docker build -f $DOCKER_FILE -t $IMAGE_NAME .
            docker run -d -p 80:80 --name $PROJECT_NAME $IMAGE_NAME
