name: Deploy Storybook via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ui-experiments
      IMAGE_TAG: latest
      DOCKER_FILE: ./docker.storybook

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          push: false
          tags: ${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}

      - name: Copy Docker image to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          env:
            APP_NAME: ${{ env.APP_NAME }}
            IMAGE_TAG: ${{ env.IMAGE_TAG }}
          script: |
            echo "Stopping existing container..."
            docker stop $APP_NAME || true
            docker rm $APP_NAME || true

            echo "Loading new image..."
            docker load < /dev/stdin

            echo "Starting new container..."
            docker run -d \
              --name $APP_NAME \
              -p 80:80 \
              --restart unless-stopped \
              $APP_NAME:$IMAGE_TAG
          stdin: ${{ steps.build.outputs.image }}
