name: Deploy Storybook

on:
  push:
    branches:
      - feature/docker-deploy

env:
  PROJECT_NAME: ui-experiments
  TAR_NAME: ${{ vars.PROJECT_NAME }}.tar
  DOCKER_FILE: ./docker.storybook

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: storybook

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f ${{ env.DOCKER_FILE }} -t ${{ env.PROJECT_NAME }} .
          docker save ${{ env.PROJECT_NAME }}:latest > ${{ env.TAR_NAME }}
          ls -sh ${{ env.TAR_NAME }}

      - name: Transfer image to server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: '${{ env.TAR_NAME }}'
          target: '/home/${{ secrets.SSH_USER }}/'

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@master
        env:
          TAR_NAME: ${{ env.TAR_NAME }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: TAR_NAME,PROJECT_NAME          
          script: |
            docker load -i $TAR_NAME
            docker run -d -p 80:80 --name $PROJECT_NAME $PROJECT_NAME:latest
